### PR TITLE
use setup_process_afterscript

### LINKED ISSUE #301: Use `methods.setup_process_afterscript()` for process logs
We should incorporate the new `methods.setup_process_afterscript()` from https://github.com/uclahs-cds/pipeline-Nextflow-config/pull/64 into this pipeline.

Under the new method, log files are automatically saved to `${params.log_output_dir}/process-log/${task.ext.log_dir}${task.ext.log_dir_suffix}/` (no need to specify a `publishDir` directive).

`${task.ext.log_dir}` defaults to `${task.process.replace(':', '/')}`.
`${task.ext.log_dir_suffix}` defaults to a blank string.

The key steps are:
1. Add `methods.setup_process_afterscript()` to `methods.setup()`.
2. For each Nextflow process:
    1. Remove the `file ".command.*"` `output` directive.
    2. Add `ext log_dir { ... }` and `ext log_sur_suffix { ... }` directives, if appropriate.
    3. Remove the `publishDir` directive with `pattern: ".command.*"`.

This pipeline does some atypical configuration with `params.workflow_log_output_dir`, but that can still be handled with `ext log_dir`:

### Current
https://github.com/uclahs-cds/pipeline-call-sSNV/blob/772592a2e11672a4901ef90f8f45978e4ea9bbae/main.nf#L74-L76

https://github.com/uclahs-cds/pipeline-call-sSNV/blob/772592a2e11672a4901ef90f8f45978e4ea9bbae/module/somaticsniper-processes.nf#L18-L21

### Updated
```diff
-    publishDir path: "${params.workflow_log_output_dir}",
-               mode: "copy",
-               pattern: ".command.*",
-               saveAs: { "${task.process.split(':')[-1]}/log${file(it).getName()}" }
+    ext log_dir { "SomaticSniper-${params.somaticsniper_version}/${task.process.split(':')[-1]}" }
```

See https://github.com/uclahs-cds/pipeline-recalibrate-BAM/pull/76/files for a full example.

### PR DESCRIPTION
**Pull request by sorelfitzgibbon**
# Description
 - This PR updates the pipeline to use the new setup_process_afterscript() method from https://github.com/uclahs-cds/pipeline-Nextflow-config/pull/64.   
 - additional log files are created for reasons I don't understand, see below.

## Testing Results

 - NFtest
    - log: /hot/software/pipeline/pipeline-call-sSNV/Nextflow/development/unreleased/sfitz-afterscript/log-nftest-20241015T222100Z.log
cases: a_mini-all-tools-std-input

These extra files are created.  
```
< process-log/intersect/compress_index_VCF_concat/check_compression_bgzip/log.command.begin
< process-log/intersect/compress_index_VCF_concat/compress_VCF_bgzip/log.command.begin
< process-log/intersect/compress_index_VCF_concat/index_VCF_tabix/log.command.begin
< process-log/intersect/compress_index_VCF_reordered/check_compression_bgzip/log.command.begin
< process-log/intersect/compress_index_VCF_reordered/index_VCF_tabix/log.command.begin
< process-log/muse/compress_index_VCF/check_compression_bgzip/log.command.begin
< process-log/muse/compress_index_VCF/index_VCF_tabix/log.command.begin
< process-log/mutect2/compress_index_VCF/check_compression_bgzip/log.command.begin
< process-log/mutect2/compress_index_VCF/index_VCF_tabix/log.command.begin
< process-log/somaticsniper/compress_index_VCF_fix/check_compression_bgzip/log.command.begin
< process-log/somaticsniper/compress_index_VCF_fix/index_VCF_tabix/log.command.begin
< process-log/somaticsniper/compress_index_VCF_hc/check_compression_bgzip/log.command.begin
< process-log/somaticsniper/compress_index_VCF_hc/compress_VCF_bgzip/log.command.begin
< process-log/somaticsniper/compress_index_VCF_hc/index_VCF_tabix/log.command.begin
< process-log/strelka2/compress_index_VCF/check_compression_bgzip/log.command.begin
< process-log/strelka2/compress_index_VCF/index_VCF_tabix/log.command.begin
```
They seem to be duplicates of the same files except including the additional (correct) tool-tool-version directory and the (correct) suffixes on the final directory.  e.g. 
```
> grep compress_index_VCF_hc after.txt 
process-log/SomaticSniper-1.0.5.0/somaticsniper/compress_index_VCF_hc/check_compression_bgzip-SNV/log.command.begin
process-log/SomaticSniper-1.0.5.0/somaticsniper/compress_index_VCF_hc/compress_VCF_bgzip-SNV/log.command.begin
process-log/SomaticSniper-1.0.5.0/somaticsniper/compress_index_VCF_hc/index_VCF_tabix-SNV/log.command.begin
process-log/somaticsniper/compress_index_VCF_hc/check_compression_bgzip/log.command.begin
process-log/somaticsniper/compress_index_VCF_hc/compress_VCF_bgzip/log.command.begin
process-log/somaticsniper/compress_index_VCF_hc/index_VCF_tabix/log.command.begin
```

I haven't been able to identify the reason and wonder if it's happening within the submodule; some kind of a default log being created as well as that specified by `log_output_dir`

# Checklist

- [x] I have read the [code review guidelines](https://uclahs-cds.atlassian.net/wiki/spaces/BOUTROSLAB/pages/3187646/Code+Review+Guidelines) and the [code review best practice on GitHub check-list](https://uclahs-cds.atlassian.net/wiki/spaces/BOUTROSLAB/pages/3189956/Code+Review+Best+Practice+on+GitHub+-+Check+List).

- [x] I have reviewed the [Nextflow pipeline standards](https://uclahs-cds.atlassian.net/wiki/spaces/BOUTROSLAB/pages/3193890/Nextflow+pipeline+standardization).

- [x] The name of the branch is meaningful and well formatted following the [standards](https://uclahs-cds.atlassian.net/wiki/spaces/BOUTROSLAB/pages/3189956/Code+Review+Best+Practice+on+GitHub+-+Check+List), using \[AD_username (or 5 letters of AD if AD is too long)]-\[brief_description_of_branch].

- [x] I have set up or verified the branch protection rule following the [github standards](https://uclahs-cds.atlassian.net/wiki/spaces/BOUTROSLAB/pages/3190380/GitHub+Standards#GitHubStandards-Branchprotectionrule) before opening this pull request.

- [x] I have added my name to the contributors listings in the ``manifest`` block in the `nextflow.config` as part of this pull request; I am listed already, or do not wish to be listed. (*This acknowledgement is optional.*)

- [x] I have added the changes included in this pull request to the `CHANGELOG.md` under the next release version or unreleased, and updated the date.

- [x] I have updated the version number in the `metadata.yaml` and `manifest` block of the `nextflow.config` file following [semver](https://semver.org/), or the version number has already been updated. (*Leave it unchecked if you are unsure about new version number and discuss it with the infrastructure team in this PR.*)

- [x] I have tested the pipeline on at least one A-mini sample.

### CODE REVIEW

**Comment by nwiltsie** [comment]
@sorelfitzgibbon You're running into the same issue as https://github.com/uclahs-cds/pipeline-Nextflow-module/pull/42 - all of our modules have `publishDir` rules built-in, so now they are being duplicated.

* `log-call-sSNV-8.1.0-20241015T222108Z/process-log/mutect2/compress_index_VCF/check_compression_bgzip/log.command.log` - Produced by the `publishDir` rule (the directory is wrong because you modified the `addParams(options: [log_output_dir: ...` line). Will **not** be produced if the command fails.
* `log-call-sSNV-8.1.0-20241015T222108Z/process-log/Mutect2-4.5.0.0/mutect2/compress_index_VCF/check_compression_bgzip-snps/log.command.log` - Produced by the afterscript, should always be produced.

My fix from https://github.com/uclahs-cds/pipeline-Nextflow-module/pull/42 was to add `ext capture_logs: false` to those processes (in the submodule, not in this repo). That ensures that _only_ the `publishDir` rule will produce the logfiles, although that means that they will _not_ be produced if the process fails.

So to fix this:
* Duplicate https://github.com/uclahs-cds/pipeline-Nextflow-module/pull/42 by adding `ext capture_logs: false` to [`check_compression_bgzip` and others](https://github.com/uclahs-cds/pipeline-Nextflow-module/blob/1cfa9fa55f043f9dbaad29d5a18d2df25890b715/modules/common/index_VCF_tabix/modules.nf#L16).
* Revert all changes to `addParams(options: [log_output_dir: ...` lines in this PR.

**Comment by nwiltsie** [comment]
> * Revert all changes to `addParams(options: [log_output_dir: ...` lines in this PR.

Actually, I'm not sure about this one... those might be right. Maybe those don't need to be reverted.

**Comment by sorelfitzgibbon** [comment]
Works now with pipeline-nextflow-module update, commit 9f07b9fee6bcd742ef8f461b62782522bb69f65e
NFtest log: `/hot/software/pipeline/pipeline-call-sSNV/Nextflow/development/unreleased/sfitz-afterscript/log-nftest-20241018T000427Z.log`
Process logs match as confirmed with `/hot/software/pipeline/pipeline-call-sSNV/Nextflow/development/unreleased/tmp.sh`

**Review by nwiltsie — APPROVED** [review]

**Pull request merged**
