### PR TITLE
Sfitz release 8.0.0 rc.1

### PR DESCRIPTION
**Pull request by sorelfitzgibbon**
# Description
Major version release since inputs and outputs are changed.
Suggested `README.md` changes included.  I'll revert if it's too much to look at right now.

## Testing Results

# Checklist

- [x] I have read the [code review guidelines](https://uclahs-cds.atlassian.net/wiki/spaces/BOUTROSLAB/pages/3187646/Code+Review+Guidelines) and the [code review best practice on GitHub check-list](https://uclahs-cds.atlassian.net/wiki/spaces/BOUTROSLAB/pages/3189956/Code+Review+Best+Practice+on+GitHub+-+Check+List).

- [x] I have reviewed the [Nextflow pipeline standards](https://uclahs-cds.atlassian.net/wiki/spaces/BOUTROSLAB/pages/3193890/Nextflow+pipeline+standardization).

- [x] The name of the branch is meaningful and well formatted following the [standards](https://uclahs-cds.atlassian.net/wiki/spaces/BOUTROSLAB/pages/3189956/Code+Review+Best+Practice+on+GitHub+-+Check+List), using \[AD_username (or 5 letters of AD if AD is too long)]-\[brief_description_of_branch].

- [x] I have set up or verified the branch protection rule following the [github standards](https://uclahs-cds.atlassian.net/wiki/spaces/BOUTROSLAB/pages/3190380/GitHub+Standards#GitHubStandards-Branchprotectionrule) before opening this pull request.

- [x] I have added my name to the contributors listings in the ``manifest`` block in the `nextflow.config` as part of this pull request; I am listed already, or do not wish to be listed. (*This acknowledgement is optional.*)

- [x] I have added the changes included in this pull request to the `CHANGELOG.md` under the next release version or unreleased, and updated the date.

- [x] I have updated the version number in the `metadata.yaml` and `manifest` block of the `nextflow.config` file following [semver](https://semver.org/), or the version number has already been updated. (*Leave it unchecked if you are unsure about new version number and discuss it with the infrastructure team in this PR.*)

- [x] I have tested the pipeline on at least one A-mini sample.

### CODE REVIEW

**Review by yashpatel6 — APPROVED** [review]
You'll want to update `nextflow.config` as well with the new version

**Comment by sorelfitzgibbon** [comment]
> You'll want to update `nextflow.config` as well with the new version

doh, why do i keep missing that.

**Comment by tyamaguchi-ucla** [comment]
> > You'll want to update `nextflow.config` as well with the new version
> 
> doh, why do i keep missing that.

Maybe we can add a check or even automate ;)

**Comment by yashpatel6** [comment]
> > > You'll want to update `nextflow.config` as well with the new version
> > 
> > 
> > doh, why do i keep missing that.
> 
> Maybe we can add a check or even automate ;)

Yeah we can probably add to the linter to add more checks

**Pull request merged**
