### PR TITLE
update M64 resources

### PR DESCRIPTION
**Pull request by sorelfitzgibbon**
# Description
Updated `M64.config` resource allocations based on results of large sample runs described [here](https://github.com/uclahs-cds/pipeline-call-sSNV/issues/288)

## Testing Results
Because this is geared towards running very large samples which can take close to 2 weeks to run, I don't want to test this branch on anything that doesn't need to be run.  I don't have any appropriate samples.

# Checklist

- [x] I have read the [code review guidelines](https://uclahs-cds.atlassian.net/wiki/spaces/BOUTROSLAB/pages/3187646/Code+Review+Guidelines) and the [code review best practice on GitHub check-list](https://uclahs-cds.atlassian.net/wiki/spaces/BOUTROSLAB/pages/3189956/Code+Review+Best+Practice+on+GitHub+-+Check+List).

- [x] I have reviewed the [Nextflow pipeline standards](https://uclahs-cds.atlassian.net/wiki/spaces/BOUTROSLAB/pages/3193890/Nextflow+pipeline+standardization).

- [x] The name of the branch is meaningful and well formatted following the [standards](https://uclahs-cds.atlassian.net/wiki/spaces/BOUTROSLAB/pages/3189956/Code+Review+Best+Practice+on+GitHub+-+Check+List), using \[AD_username (or 5 letters of AD if AD is too long)]-\[brief_description_of_branch].

- [x] I have set up or verified the branch protection rule following the [github standards](https://uclahs-cds.atlassian.net/wiki/spaces/BOUTROSLAB/pages/3190380/GitHub+Standards#GitHubStandards-Branchprotectionrule) before opening this pull request.

- [x] I have added my name to the contributors listings in the ``manifest`` block in the `nextflow.config` as part of this pull request; I am listed already, or do not wish to be listed. (*This acknowledgement is optional.*)

- [x] I have added the changes included in this pull request to the `CHANGELOG.md` under the next release version or unreleased, and updated the date.

- [x] I have updated the version number in the `metadata.yaml` and `manifest` block of the `nextflow.config` file following [semver](https://semver.org/), or the version number has already been updated. (*Leave it unchecked if you are unsure about new version number and discuss it with the infrastructure team in this PR.*)

- [ ] I have tested the pipeline on at least one A-mini sample.

### CODE REVIEW

**Comment by tyamaguchi-ucla** [comment]
@sorelfitzgibbon Thanks! Let me test it out for my large samples.

**Comment by tyamaguchi-ucla** [comment]
**question (non-blocking):**
@sorelfitzgibbon @yashpatel6 I just noticed that the `template.config` has the `work_dir` param. I thought we've removed this from our NF pipelines to prevent the latency issue a while ago. Is there any reason we want to keep it in the `template.config` in this pipeline?

**Comment by yashpatel6** [comment]
> **question (non-blocking):** @sorelfitzgibbon @yashpatel6 I just noticed that the `template.config` has the `work_dir` param. I thought we've removed this from our NF pipelines to prevent the latency issue a while ago. Is there any reason we want to keep it in the `template.config` in this pipeline?

Ah good catch, there shouldn't be any reason to keep that in the template in this pipeline; @sorelfitzgibbon it should be remove-able from the template here?

**Comment by sorelfitzgibbon** [comment]
> @sorelfitzgibbon it should be remove-able from the template here?

done

**Comment by tyamaguchi-ucla** [comment]
This config finally worked. I'll try other large samples.

**Review by tyamaguchi-ucla — APPROVED** [review]
I was able to process the large samples.

**Pull request merged**
